### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [Alberto97/AlwaysOnDisplayToggle#1]
Currently the app available on [izzy-repo](https://apt.izzysoft.de/fdroid/index/apk/org.alberto97.aodtoggle).

Would you consider putting this app on F-Droid, please?
Thank you.

**Comment by Alberto97** [comment]
Well, until [just few days ago](https://github.com/Alberto97/AlwaysOnDisplayToggle/commit/4b2fd230c9ae8ce5156dfea674c10d715307c0b6) this was supposed to be just for personal usage (which in my case has been superceeded by an option in Google's Digital Wellbeing) but lately it seems that the app gained the interest of few people and if someone else wants to use it, sure, I'm happy to help.
That being said I won't be attaching apks in Github releases anymore (I believe there won't be many though). The effort of doing that would outweigh the gains for me since I'd have to setup different builds with different signatures.

**Comment by Alberto97** [comment]
Request for packaging [#2045](https://gitlab.com/fdroid/rfp/-/issues/2045) opened

**Comment by Alberto97** [comment]
The app has been approved and will appear on F-Droid in few days :blush:
